version: '3'
services:
  web:
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: postgres:15
    restart: no
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${USERNAME}